apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: hub-preprocess-azure-kv-populate
spec:
  remediationAction: enforce
  severity: medium
  pruneObjectBehavior: DeleteIfCreated
  object-templates-raw: |

    - complianceType: mustnothave
      objectDefinition:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: fake-policy-holder
          namespace: acm-policies
        data:
          fake: holder so policy is not generated empty

    {{- $secrets := (lookup "v1" "Secret" "eso-secret-store" "" "eso-category").items }}
    {{- range $eso_secret := $secrets }}
    {{- if (and (not (dig "appId" "" $eso_secret.data | empty)) (not (dig "appPassword" "" $eso_secret.data | empty)) (not (dig "tenantId" "" $eso_secret.data | empty)) (not (dig "tenantUrl" "" $eso_secret.data | empty))) }}

    - complianceType: mustonlyhave
      objectDefinition:
        kind: Secret
        apiVersion: v1
        metadata:
          name: "{{ $eso_secret.metadata.name }}"
          namespace: acm-policies
          labels:
          {{- range $kLabel, $vLabel := $eso_secret.metadata.labels }}
            "{{ $kLabel }}": "{{ $vLabel }}"
          {{- end }}
        data:
        {{- range $kData, $vData := $eso_secret.data }}
          "{{ $kData }}": "{{ $vData }}"
        {{- end }}

    {{- end }}
    {{- end }}
