apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - gitops-cluster.yaml
  - acm-rbac.yaml
patches:
  - path: argocd-patch.yaml
    target:
      kind: ArgoCD
