apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: cluster
spec:
  prometheus:
    enabled: true
    service:
      port: 8080
  replicaCount: 3
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: "2"
      memory: 2Gi
  certController:
    replicaCount: 2
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: "1"
        memory: 1Gi
  webhook:
    replicaCount: 2
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: "1"
        memory: 1Gi
  crds:
    createClusterExternalSecret: false
    createClusterSecretStore: false
    createPushSecret: false
